### ISSUE TITLE
Docker volume setup is not working as is

### ISSUE THREAD

**Issue by etienne-napoleone** [tomochain/create-tomochain-masternode#12]
It creates a docker-compose.yml file with the following line it it:
`$DATA:/tomochain/data/tomo/chaindata`
In order for tomo to work properly though, the above line needs to be:
`$DATA:/tomochain/data`

I'll work on it asap and submit a PR

**Comment by thanhson1085** [comment]
After investigate, i think current config is correct
https://github.com/tomochain/create-tomochain-masternode/blob/327d63551efc93d27629b675bd9ed77db9be2e93/create_tomochain_masternode/templates/compose.py#L17

**Comment by thanhson1085** [comment]
fixed by https://github.com/tomochain/create-tomochain-masternode/commit/c56a7a5f9767d9d820e8862b6f7eac88363e6a61
